version: 2
jobs:
  build:
     working_directory: ~/podam

     docker:
        - image: circleci/openjdk:8-jdk

     steps:
        - checkout
  
        - run: 
            name: clean and verify
            command: mvn clean verify
            when: always

        - run:
            name: Save test results 
            command: |
              mkdir -p ~/junit/ 
              find . -type f -regex ".*/target/failsafe-reports/.*xml" -exec cp {} ~/junit/ \;
            when: always
        - store_test_results:
            path: ~/junit
        - store_artifacts:
            path: ~/junit
